version: '3.3'

services:
  pg_database:
    container_name: pg_database
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n0t_Publ1c}
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - app-network

  # web_admin:
  #   container_name: web_admin
  #   build:
  #     context: ./src/web_admin
  #     dockerfile: Dockerfile
  #   environment:
  #     - VITE_API_URL=http://localhost:81/api
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  web_api:
    container_name: web_api
    build:
      context: ./src/web_api
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  web_server:
    image: nginx:alpine
    container_name: web_server
    # depends_on:
    #   - web_admin
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
    networks:
      - app-network
    restart: unless-stopped

#Docker Networks
networks:
  app-network:
    driver: bridge